### ISSUE TITLE
Option to make `.new` private

### ISSUE THREAD

**Issue by americodls** [snusnu/procto#6]
I frequently use method objects like these:

```ruby
class Greeter
  private_class_method :new
  
  def self.call(text)
    new(text).call
  end

  def initialize(text)
    @text = text
  end

  def call
    "Hello #{@text}"
  end
end
```

I add the `private_class_method :new` to avoid to another developers that does not understand the pattern instantiate the object manually.

What do you think about it?

**Comment by mbj** [comment]
> What do you think about it?

Fine from my side. Also we should allow `#call` to be private, so use `__send__` from the singleton level.

**Comment by americodls** [comment]
I think to make `#call` private it is not necessary since the object could not be instantiated out of the class context using `private_class_method :new`.

**Comment by mbj** [comment]
@americodls If a method has no public call side the form `foo.call` it should be private for consistency.

**Comment by americodls** [comment]
@mbj I fully agree with that.

But, look at line 5: `new(text).call`. It has a public call. That's why you suggest to use `__send__`.

**Comment by mbj** [comment]
Yes. But that public call side is "private" in nature in regards to the only public API `some_class.call`. Hence I think its clearer to document the intent not having the instance level `#call` public in the first place.

**Comment by americodls** [comment]
@mbj

When `.new` is made private, the intention will be clear:

You don't have to instantiate this object.

As the object cannot be instantianted the user doesn't have how to call its methods.

`#call` will be public only to the class. Another instance methods must be private in order to communicate the class that `#call` is the entry point.

We can avoid the use of  `__send__` just making `.new` private.

**Comment by mbj** [comment]
@americodls I like this discussion.

Still I think that it makes sense to have `#call` private, as inside the `procto` (infected) object, there could be a call side that leaks `self` to somewhere (by accident) and there it should not have public methods, like `#call`.

The idea is to use the least powerful primitive, a private method is more "primitive" in that sense. I'm fine to pay the extra cost of `__send__` as an additional guarantee level.

**Comment by americodls** [comment]
@mbj Sorry, I have no idea how this could happen.

I think, if it happens, the blame could not be on the design that I proposed (the problem is certainly in the misuse of the gem).
It seems that you is trying to solve a problem that doesn't exists yet. I can't agree with that.

I think my arguments are over and we reached the end of discussion here. Thank you for your time.

**Comment by mbj** [comment]
@americodls 

```ruby
class Foo
  include Proto.call

 def call
   SomeClass.new(self) # may call `#call` which is a mistake
 end
end 
```

**Comment by americodls** [comment]
@mbj You have a point. I get it. I am convinced. 👍

**Comment by mbj** [comment]
@americodls I like discussions like these. They keep me sharp, thx for disagreeing!
